"""initial schema

Revision ID: afbbb605a9b3
Revises: 
Create Date: 2026-06-12 12:28:38.507912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afbbb605a9b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_config',
    sa.Column('category_dashboard', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('category_dashboard')
    )
    op.create_table('forecast_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('days_ahead', sa.Integer(), nullable=False),
    sa.Column('exclude_categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('exclude_tx_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_overrides',
    sa.Column('merchant_clean', sa.String(length=255), nullable=False),
    sa.Column('category_dashboard', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('merchant_clean')
    )
    op.create_table('ml_training_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('category_distribution', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ynab_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_raw', sa.Text(), nullable=False),
    sa.Column('merchant_clean', sa.Text(), nullable=True),
    sa.Column('category_ynab', sa.String(length=255), nullable=True),
    sa.Column('category_dashboard', sa.String(length=255), nullable=True),
    sa.Column('category_source', sa.String(length=50), nullable=True),
    sa.Column('ml_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ynab_approved', sa.Boolean(), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category_dashboard'), 'transactions', ['category_dashboard'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_ynab_transaction_id'), 'transactions', ['ynab_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_ynab_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_dashboard'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('ml_training_log')
    op.drop_table('merchant_overrides')
    op.drop_table('forecast_scenarios')
    op.drop_table('budget_config')
    # ### end Alembic commands ###
