services:
  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
#  frontend:
#    volumes:
#      - ./frontend/src:/app/src  # Vite HMR
#    ports:
#      - "3000:3000"
  postgres:
    ports:
      - "5432:5432"          # direct DB access from host tools
